### ISSUE TITLE
[Bug] emby 更新1.0.25后 刷不出来

### ISSUE THREAD

**Issue by icepark2020** [metatube-community/jellyfin-plugin-metatube#123]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2022.1218.1400.0

### MetaTube Server Version

1.0.25

### What OS are you seeing the problem on?

Linux, Other

### Description

emby版本 4.7.10.0 用以前的javtube v2022.1130.1150.0 配合1.0.24 可以正常识别，

卸载了javtube。换了matetube后就刷不出来

### MetaTube Server

[GORM] 2023/01/17 12:49:00 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
[0.289ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "ipz-921" COLLATE NOCASE OR id = "ipz-921" COLLATE NOCASE
[GIN] 2023/01/17 - 12:49:00 | 200 |  2.697890221s |  219.78.214.155 | GET      "/v1/movies/search?q=ipz-921-C&provider=&fallback=True"
[GIN] 2023/01/17 - 12:49:00 | 404 |      48.501µs |  219.78.214.155 | GET      "/v1/movies?lazy=True"
[GORM] 2023/01/17 12:49:04 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
[0.310ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "ipz-921" COLLATE NOCASE OR id = "ipz-921" COLLATE NOCASE
[GIN] 2023/01/17 - 12:49:04 | 200 |  2.868116338s |  219.78.214.155 | GET      "/v1/movies/search?q=ipz-921-C&provider=&fallback=True"
[GIN] 2023/01/17 - 12:49:04 | 404 |      55.401µs |  219.78.214.155 | GET      "/v1/movies?lazy=True"
[GORM] 2023/01/17 12:49:07 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
[0.377ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "ABW-153" COLLATE NOCASE OR id = "ABW-153" COLLATE NOCASE
[GIN] 2023/01/17 - 12:49:07 | 200 |  2.510573774s |  219.78.214.155 | GET      "/v1/movies/search?q=ABW-153&provider=&fallback=True"
[GIN] 2023/01/17 - 12:49:08 | 404 |      51.601µs |  219.78.214.155 | GET      "/v1/movies?lazy=True"

### Jellyfin/Emby Logs

2023-01-17 20:48:57.351 Debug App: Running MovieImageProvider for /unraid_video/18+/日本/ABW-153/ABW-153.mp4
2023-01-17 20:48:57.383 Debug App: Running FFProbeProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:48:57.383 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2023-01-17 20:48:57.391 Debug MediaProbeManager: ProcessRun 'ffprobe' Started.
2023-01-17 20:48:57.583 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2023-01-17 20:48:57.589 Debug App: Running MovieNfoProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:48:57.589 Debug App: MovieNfoProvider returned no metadata for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:48:57.589 Debug App: Running MovieProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:48:57.589 Info MetaTube.MovieProvider: Search for movie: ipz-921-C
2023-01-17 20:49:00.568 Info MetaTube.MovieProvider: Get movie info: :
2023-01-17 20:49:00.845 Error App: Error in MetaTube
	*** Error Report ***
	Version: 4.7.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-Unraid (root@Develop) (gcc (GCC) 12.2.0, GNU ld version 2.39-slack151) #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: API request error: 404 (Not Found)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: MetaTube
	TargetSite: Void MoveNext()
	
2023-01-17 20:49:00.845 Debug App: Running MovieImageProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:49:00.932 Debug App: FolderImageProvider reports change to 52441 - /unraid_video/18+/日本/mide-767
2023-01-17 20:49:00.932 Debug App: Running FolderImageProvider for /unraid_video/18+/日本/mide-767
2023-01-17 20:49:00.997 Debug SqliteItemRepository: Public GetItemLinks
2023-01-17 20:49:00.997 Debug App: Running FFProbeProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:49:00.997 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2023-01-17 20:49:01.004 Debug MediaProbeManager: ProcessRun 'ffprobe' Started.
2023-01-17 20:49:01.142 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2023-01-17 20:49:01.149 Debug App: Running MovieNfoProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:49:01.149 Debug App: MovieNfoProvider returned no metadata for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:49:01.149 Debug App: Running MovieProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:49:01.149 Info MetaTube.MovieProvider: Search for movie: ipz-921-C
2023-01-17 20:49:01.567 Debug Server: http/1.1 GET http://host3:1900/embywebsocket?deviceId=2934216c-39a6-4657-b5fc-04e1b4f8cbf0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:01.567 Debug Server: http/1.1 Response 404 to host4. Time: 0ms. http://host3:1900/embywebsocket?deviceId=2934216c-39a6-4657-b5fc-04e1b4f8cbf0
2023-01-17 20:49:03.765 Debug Server: http/1.1 GET http://host3:1900/web/manifest.json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:03.765 Debug Server: http/1.1 Response 304 to host4. Time: 0ms. http://host3:1900/web/manifest.json
2023-01-17 20:49:04.277 Debug Server: http/1.1 GET http://host3:1900/emby/system/info/public. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.277 Debug Server: http/1.1 Response 200 to host4. Time: 0ms. http://host3:1900/emby/system/info/public
2023-01-17 20:49:04.306 Debug Server: http/1.1 GET http://host3:1900/emby/System/Info. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.306 Debug Server: http/1.1 Response 200 to host4. Time: 1ms. http://host3:1900/emby/System/Info
2023-01-17 20:49:04.313 Info MetaTube.MovieProvider: Get movie info: :
2023-01-17 20:49:04.324 Debug Server: http/1.1 GET http://host3:1900/emby/DisplayPreferences/usersettings?userId=8b8d368bf8ef4bcb948344da306a9ffc&client=emby&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.325 Debug Server: http/1.1 Response 200 to host4. Time: 1ms. http://host3:1900/emby/DisplayPreferences/usersettings?userId=8b8d368bf8ef4bcb948344da306a9ffc&client=emby&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0
2023-01-17 20:49:04.326 Debug Server: http/1.1 GET http://host3:1900/embywebsocket?deviceId=2934216c-39a6-4657-b5fc-04e1b4f8cbf0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.326 Debug Server: http/1.1 Response 404 to host4. Time: 0ms. http://host3:1900/embywebsocket?deviceId=2934216c-39a6-4657-b5fc-04e1b4f8cbf0
2023-01-17 20:49:04.359 Info Server: http/1.1 POST http://host3:1900/emby/Sessions/Capabilities/Full?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.360 Debug AuthenticationRepository: UpdateCapabilities id: 124
2023-01-17 20:49:04.360 Info Server: http/1.1 Response 204 to host4. Time: 1ms. http://host3:1900/emby/Sessions/Capabilities/Full?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0&reqformat=json
2023-01-17 20:49:04.366 Debug Server: http/1.1 GET http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.367 Debug Server: http/1.1 Response 200 to host4. Time: 1ms. http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0
2023-01-17 20:49:04.423 Debug Server: http/1.1 GET http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc/Items/30140?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.426 Debug Server: http/1.1 GET http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc/Views?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.428 Debug Server: http/1.1 Response 200 to host4. Time: 2ms. http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc/Views?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0
2023-01-17 20:49:04.446 Debug SqliteItemRepository: GetSubviews total time: 22.5554ms
2023-01-17 20:49:04.446 Debug Server: http/1.1 Response 200 to host4. Time: 24ms. http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc/Items/30140?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0
2023-01-17 20:49:04.571 Debug Server: http/1.1 GET http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc/Items?SortBy=DateCreated,SortName&SortOrder=Descending&IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo,CanDelete,Container,PrimaryImageAspectRatio,ProductionYear&StartIndex=0&ParentId=30140&EnableImageTypes=Primary,Backdrop,Thumb&ImageTypeLimit=1&Limit=50&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
2023-01-17 20:49:04.583 Debug Server: http/1.1 Response 200 to host4. Time: 12ms. http://host3:1900/emby/Users/8b8d368bf8ef4bcb948344da306a9ffc/Items?SortBy=DateCreated,SortName&SortOrder=Descending&IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo,CanDelete,Container,PrimaryImageAspectRatio,ProductionYear&StartIndex=0&ParentId=30140&EnableImageTypes=Primary,Backdrop,Thumb&ImageTypeLimit=1&Limit=50&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=2934216c-39a6-4657-b5fc-04e1b4f8cbf0&X-Emby-Client-Version=4.7.10.0
2023-01-17 20:49:04.618 Error App: Error in MetaTube
	*** Error Report ***
	Version: 4.7.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-Unraid (root@Develop) (gcc (GCC) 12.2.0, GNU ld version 2.39-slack151) #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: API request error: 404 (Not Found)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: MetaTube
	TargetSite: Void MoveNext()
	
2023-01-17 20:49:04.618 Debug App: Running MovieImageProvider for /unraid_video/18+/日本/ipz-921-C/ipz-921-C.mp4
2023-01-17 20:49:04.876 Debug SqliteItemRepository: Public GetItemLinks
2023-01-17 20:49:04.876 Debug App: Running FFProbeProvider for /unraid_video/18+/日本/ABW-153/ABW-153.mp4
2023-01-17 20:49:04.877 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/unraid_video/18+/日本/ABW-153/ABW-153.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2023-01-17 20:49:04.979 Debug MediaProbeManager: ProcessRun 'ffprobe' Started.
2023-01-17 20:49:05.176 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2023-01-17 20:49:05.179 Debug App: Running MovieNfoProvider for /unraid_video/18+/日本/ABW-153/ABW-153.mp4
2023-01-17 20:49:05.179 Debug App: MovieNfoProvider returned no metadata for /unraid_video/18+/日本/ABW-153/ABW-153.mp4
2023-01-17 20:49:05.179 Debug App: Running MovieProvider for /unraid_video/18+/日本/ABW-153/ABW-153.mp4
2023-01-17 20:49:05.179 Info MetaTube.MovieProvider: Search for movie: ABW-153
2023-01-17 20:49:07.971 Info MetaTube.MovieProvider: Get movie info: :
2023-01-17 20:49:08.248 Error App: Error in MetaTube
	*** Error Report ***
	Version: 4.7.10.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.19.17-Unraid (root@Develop) (gcc (GCC) 12.2.0, GNU ld version 2.39-slack151) #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: API request error: 404 (Not Found)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: MetaTube
	TargetSite: Void MoveNext()
	
2023-01-17 20:49:08.248 Debug App: Running MovieImageProvider for /unraid_video/18+/日本/ABW-153/ABW-153.mp4
2023-01-17 20:49:08.259 Debug App: Saving nfo metadata for /unraid_video/18+/日本/ABW-153/ABW-153.mp4 to /unraid_video/18+/日本/ABW-153/ABW-153.nfo.
2023-01-17 20:49:12.803 Debug Server: http/1.1 GET http://host1:8920/emby/System/Logs/embyserver.txt. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55

### MetaTube Server Logs

[GORM] 2023/01/17 12:49:00 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
[0.289ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "ipz-921" COLLATE NOCASE OR id = "ipz-921" COLLATE NOCASE
[GIN] 2023/01/17 - 12:49:00 | 200 |  2.697890221s |  219.78.214.155 | GET      "/v1/movies/search?q=ipz-921-C&provider=&fallback=True"
[GIN] 2023/01/17 - 12:49:00 | 404 |      48.501µs |  219.78.214.155 | GET      "/v1/movies?lazy=True"
[GORM] 2023/01/17 12:49:04 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
[0.310ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "ipz-921" COLLATE NOCASE OR id = "ipz-921" COLLATE NOCASE
[GIN] 2023/01/17 - 12:49:04 | 200 |  2.868116338s |  219.78.214.155 | GET      "/v1/movies/search?q=ipz-921-C&provider=&fallback=True"
[GIN] 2023/01/17 - 12:49:04 | 404 |      55.401µs |  219.78.214.155 | GET      "/v1/movies?lazy=True"
[GORM] 2023/01/17 12:49:07 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
[0.377ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "ABW-153" COLLATE NOCASE OR id = "ABW-153" COLLATE NOCASE
[GIN] 2023/01/17 - 12:49:07 | 200 |  2.510573774s |  219.78.214.155 | GET      "/v1/movies/search?q=ABW-153&provider=&fallback=True"
[GIN] 2023/01/17 - 12:49:08 | 404 |      51.601µs |  219.78.214.155 | GET      "/v1/movies?lazy=True"

**Comment by iamckun** [comment]
我也遇到了没人解答，你是已经解决了嘛咋回事啊
