### ISSUE TITLE
[Bug] 扫描媒体库日志报错

### ISSUE THREAD

**Issue by catch6** [metatube-community/jellyfin-plugin-metatube#132]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2022.1218.1400.0

### MetaTube Server Version

1.0.25

### What OS are you seeing the problem on?

Linux

### Description

jellyfin 版本 10.8.9，在更新媒体元数据时报错

### Jellyfin/Emby Logs

```
[2023-02-14 11:13:16.943 +00:00] [INF] [86] Emby.Server.Implementations.IO.LibraryMonitor: "ST" ("/media/ST") will be refreshed.
[2023-02-14 11:13:17.011 +00:00] [INF] [86] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "JUY-641 後ろから私をメチャクチャにして…。～人妻の犯●れ願望を満たすバック性交～ 宝生リリー", Path: "/media/ST/JUY-641-C.mp4", Id: ffe66130-d926-8b76-bf9f-2513c26facb6
[2023-02-14 11:13:17.288 +00:00] [INF] [86] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "SSIS-586 出張先で軽蔑している中年セクハラ上司とまさかの相部屋に…朝まで続く絶倫性交に不覚にも感じてしまった私 河北彩花", Path: "/media/ST/SSIS-586-C.mp4", Id: 469c073e-1a77-f072-1bde-eb43275d616d
[2023-02-14 11:13:18.577 +00:00] [INF] [86] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Get movie info: "FC2:3061625"
[2023-02-14 11:13:19.191 +00:00] [ERR] [19] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(IDatabaseConnection db, IEnumerable`1 tuples)
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass68_0.<<RefreshChildMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Providers.Manager.ProviderManager.RunMetadataRefresh(Func`1 action, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass70_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

**Comment by catch6** [comment]
看报错信息应该是某个字段为 null 了，是否可以填充空字符串，现在会导致扫描中断，后面的媒体也没有扫描到

**Comment by xjasonlyu** [comment]
是的，会尽快修复。

**Comment by catch6** [comment]
谢谢 @xjasonlyu

**Comment by xjasonlyu** [comment]
此问题应该已经修复了，尝试更新插件即可。
