### ISSUE TITLE
[Bug] AVBASE 無法刮削

### ISSUE THREAD

**Issue by Dissyu** [metatube-community/jellyfin-plugin-metatube#166]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.503.910.0

### MetaTube Server Version

v1.0.28

### Description

AVBASE有部分影片明明有在該網站中，但無法正常刮削

### Jellyfin/Emby Logs

[01:31:39] [INF] [257] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: stars-829
[01:31:44] [ERR] [255] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube
System.Exception: API request error: 500 (provider not found)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

### MetaTube Server Logs

2023/05/06 01:33:51 [Recovery] 2023/05/06 - 01:33:51 panic recovered:
provider not found
github.com/metatube-community/metatube-sdk-go/engine/engine.go:157 (0xf7f4f3)
github.com/metatube-community/metatube-sdk-go/engine/movie.go:145 (0xf82309)
github.com/metatube-community/metatube-sdk-go/engine/movie.go:165 (0xf81bc1)
github.com/metatube-community/metatube-sdk-go/route/search.go:64 (0xf95fd1)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0xf93d17)
github.com/metatube-community/metatube-sdk-go/route/auth.go:26 (0xf93c89)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0xf94afc)
github.com/metatube-community/metatube-sdk-go/route/redirect.go:59 (0xf948bf)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x924861)
github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x92484c)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x923986)
github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x923969)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x922a0a)
github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x922691)
github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x9221bc)
net/http/server.go:2936 (0x6e0c95)
net/http/server.go:1995 (0x6dc1b1)
runtime/asm_amd64.s:1598 (0x467520)

[GIN] 2023/05/06 - 01:33:51 | 500 |   2.04237232s |      172.17.0.1 | GET      "/v1/movies/search?q=stars-829&provider=&fallback=True"

**Comment by Dissyu** [comment]
已解決，更新完plugin和server後，重啟Jellyfin即可 .....
