### ISSUE TITLE
[Bug] ffmpeg failed

### ISSUE THREAD

**Issue by Neurotoxin0** [metatube-community/jellyfin-plugin-metatube#186]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.503.910.0

### MetaTube Server Version

1.1.0

### What OS are you seeing the problem on?

Linux

### Description

*** Error Report ***
	Version: 4.7.11.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 4.4.302+ (root@build7) (gcc version 12.2.0 (GCC) ) #64570 SMP Sat Jun 3 00:09:29 CST 2023
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: API request error: 404 (info not found)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: MetaTube
	TargetSite: Void MoveNext()

### Jellyfin/Emby Logs

*** Error Report ***
	Version: 4.7.11.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 4.4.302+ (root@build7) (gcc version 12.2.0 (GCC) ) #64570 SMP Sat Jun 3 00:09:29 CST 2023
	Framework: .NET 6.0.8
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Exception: System.Exception: API request error: 404 (info not found)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: MetaTube
	TargetSite: Void MoveNext()

**Comment by chuanshuojibi** [comment]
the freeserver is not stable, sometimes you can connect it , sometimes not,and i once connect well but the nextday it failed and i even can't view the emby pages

**Comment by Neurotoxin0** [comment]
> the freeserver is not stable, sometimes you can connect it , sometimes not,and i once connect well but the nextday it failed and i even can't view the emby pages

I'm not using the free server however

**Comment by chuanshuojibi** [comment]
> > the freeserver is not stable, sometimes you can connect it , sometimes not,and i once connect well but the nextday it failed and i even can't view the emby pages
> 
> I'm not using the free server however
##proxy
It's very likely that the issue lies with your backend network. The backend, in fact, is a service program that makes API requests. Improper usage of proxies in your backend might prevent it from connecting. Yesterday, I tried using a free backend, and even though I could ping and access it without proxies, I still couldn't retrieve images. However, once I added proxies to Emby, I successfully fetched the images.

**Comment by chuanshuojibi** [comment]
It's very likely that the issue lies with your server network. The server, in fact, is a service program that makes API requests. Improper usage of proxies in your server might prevent it from connecting. Yesterday, I tried using a free server, and even though I could ping and access it without proxies, I still couldn't retrieve images. However, once I added proxies to Emby, I successfully fetched the images.

**Comment by chuanshuojibi** [comment]
> > the freeserver is not stable, sometimes you can connect it , sometimes not,and i once connect well but the nextday it failed and i even can't view the emby pages
> 
> I'm not using the free server however

It's very likely that the issue lies with your server network. The server, in fact, is a service program that makes API requests. Improper usage of proxies in your server might prevent it from connecting. Yesterday, I tried using a free server, and even though I could ping and access it without proxies, I still couldn't retrieve images. However, once I added proxies to Emby, I successfully fetched the images.the free server url I use is " https://metatube.pyhdxy.com/ "  you can try it with proxy  added to embyserver container 
那很可能就是你后台的网络问题了,后台实际上还是一个请求api的服务程序,你的后台如果不恰当的使用代理可能就无法连上,我昨天尝试去使用了免费的后台,在我未添加代理时即使我可以ping通后台并且访问,依旧无法获取图片,而在我给emby添加代理后,我就成功的搜刮到了图片,我使用的是提供的免费后台  https://metatube.pyhdxy.com/ 你可以给docker容器添加翻墙代理后使用他
