### ISSUE TITLE
[Bug] 老老实实配置了，结果似乎是没连上后端？

### ISSUE THREAD

**Issue by kklod** [metatube-community/jellyfin-plugin-metatube#216]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.1013.2110.0

### MetaTube Server Version

metatube-server:latest

### What OS are you seeing the problem on?

Windows

### Description

后端部署在Debiandocker，emby安装在win上
刮削没反应……单个影片手动识别也搜不到东西
后端部署后感觉就没动过～～有设置好代理的～～
有没有大佬帮忙看下？

### MetaTube Server

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GIN_MODE=release
PORT=8080
TOKEN=1234567
DSN=
REQUEST_TIMEOUT=
DB_MAX_IDLE_CONNS=0
DB_MAX_OPEN_CONNS=0
DB_PREPARED_STMT=0
DB_AUTO_MIGRATE=0
HTTP_PROXY=http://20.0.0.2:7890
HTTPS_PROXY=http://20.0.0.2:7890

### Jellyfin/Emby Logs

====部分======
2023-10-18 16:24:08.816 Info MetaTube.MovieProvider: Search for movie: CLOT-011
2023-10-18 16:24:08.825 Error App: Error in MetaTube
	*** Error Report ***
	Version: 4.7.14.0
	Command line: C:\Users\Administrator\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows 10.0.19045
	Framework: .NET 6.0.21
	OS/Process: x64/x64
	Runtime: C:/Users/Administrator/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: C:\Users\Administrator\AppData\Roaming\Emby-Server\programdata
	Application path: C:\Users\Administrator\AppData\Roaming\Emby-Server\system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
	 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
	   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
	   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
	Source: System.Net.Security
	TargetSite: Int32 GetFrameSize(System.ReadOnlySpan`1[System.Byte])
	   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
	   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

### MetaTube Server Logs

[GORM] 2023/10/18 07:54:32 github.com/glebarez/sqlite@v1.9.0/migrator.go:33
[1.479ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_metadata"
[GORM] 2023/10/18 07:54:32 github.com/glebarez/sqlite@v1.9.0/migrator.go:111
[0.835ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "movie_metadata" AND sql IS NOT NULL order by type = "table" desc
[GORM] 2023/10/18 07:54:32 github.com/glebarez/sqlite@v1.9.0/migrator.go:119
[0.644ms] [rows:-] SELECT * FROM `movie_metadata` LIMIT 1
[GORM] 2023/10/18 07:54:32 github.com/glebarez/sqlite@v1.9.0/migrator.go:33
[0.286ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="actor_metadata"
[GORM] 2023/10/18 07:54:32 github.com/glebarez/sqlite@v1.9.0/migrator.go:111
[0.797ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "actor_metadata" AND sql IS NOT NULL order by type = "table" desc
[GORM] 2023/10/18 07:54:32 github.com/glebarez/sqlite@v1.9.0/migrator.go:119
[0.569ms] [rows:-] SELECT * FROM `actor_metadata` LIMIT 1

**Comment by SoulMateK** [comment]
我也遇到类似的问题了，访问api接口，可以正常返回数据，但是emby拉不到数据

**Comment by SoulMateK** [comment]
我这边发现原因了，插件有个filter的开关，把他取消勾选就行了

**Comment by kklod** [comment]
> 我这边发现原因了，插件有个filter的开关，把他取消勾选就行了

我本来就未勾选filter~~

**Comment by kakolukia** [comment]
部署在 koyeb，碰到类似的问题了
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/30426497/703e2710-3cf8-4750-8228-3833f286df0a)

**Comment by kakolukia** [comment]
> 部署在 koyeb，下面贴的是 koyeb 的 log，之前除了FC2的会404导致无法刮削其他一直ok，今天发现碰到类似楼主的问题了。手动识别可以看到结果，但点选了某个源后也是无法完成拉取。 ![image](https://user-images.githubusercontent.com/30426497/277623941-703e2710-3cf8-4750-8228-3833f286df0a.png)

换了一下 filter 顺序，发现我这个的问题了，是 AVBASE 刮削的问题，望修复。AVBASE 图片和演员一直比较准确。
