### ISSUE TITLE
[Bug] emby最新测试版本已经无法使用

### ISSUE THREAD

**Issue by Duan-rax** [metatube-community/jellyfin-plugin-metatube#217]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1013.2110.0

### MetaTube Server Version

1.1.3

### Description

2023-10-31 19:27:31.139 Info TaskManager: Executing Organize Metadata
2023-10-31 19:27:31.151 Error TaskManager: Error
        *** Error Report ***
        Version: 4.8.0.57
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
        Operating system: Linux version 5.10.0-23-arm64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1
        Framework: .NET 6.0.20
        OS/Process: arm64/arm64
        Runtime: opt/emby-server/system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /var/lib/emby
        Application path: /opt/emby-server/system
        System.TypeLoadException: System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Sorting.SortExtensions' from assembly 'MediaBrowser.Controller, Version=4.8.0.57, Culture=neutral, PublicKeyToken=null'.
           at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
           at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
        Source: MetaTube
        TargetSite: Void MoveNext()

2023-10-31 19:27:31.151 Info TaskManager: Organize Metadata Failed after 0 minute(s) and 0 seconds

### MetaTube Server

无报错

### Jellyfin/Emby Logs

2023-10-31 19:27:31.139 Info TaskManager: Executing Organize Metadata
2023-10-31 19:27:31.151 Error TaskManager: Error
        *** Error Report ***
        Version: 4.8.0.57
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
        Operating system: Linux version 5.10.0-23-arm64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1
        Framework: .NET 6.0.20
        OS/Process: arm64/arm64
        Runtime: opt/emby-server/system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /var/lib/emby
        Application path: /opt/emby-server/system
        System.TypeLoadException: System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Sorting.SortExtensions' from assembly 'MediaBrowser.Controller, Version=4.8.0.57, Culture=neutral, PublicKeyToken=null'.
           at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
           at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
        Source: MetaTube
        TargetSite: Void MoveNext()

2023-10-31 19:27:31.151 Info TaskManager: Organize Metadata Failed after 0 minute(s) and 0 seconds

### MetaTube Server Logs

无logs，似乎未连接

### How to Reproduce

emby升级最新测试版，计划任务-Organize Metadata即报错

**Comment by kk77mgj** [comment]
这插件只适配emby正式版的，测试版不一定支持。

**Comment by Duan-rax** [comment]
> 这插件只适配emby正式版的，测试版不一定支持。

是的，我重新查看了wiki，经测试4.8.0.56后不再支持，大家升级版本需谨慎

**Comment by xjasonlyu** [comment]
Emby `4.8.0.57-beta` 更新了才不到19小时，官方nuget的API库都没上传上去，这边想要适配都难。由于beta版更新频繁，所以不保证插件对测试版的兼容性。
