### ISSUE TITLE
[Bug] ould not load type

### ISSUE THREAD

**Issue by 3071776** [metatube-community/jellyfin-plugin-metatube#231]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1013.2110.0

### MetaTube Server Version

2023.1013.2110.0

### What OS are you seeing the problem on?

Linux

### Description

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/5479426/64313fca-b191-4a0c-8c13-c1298d7a373a)

### Jellyfin/Emby Logs

 System.TypeLoadException: System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Sorting.SortExtensions' from assembly 'MediaBrowser.Controller, Version=4.8.0.58, Culture=neutral, PublicKeyToken=null'.
           at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
           at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
        Source: MetaTube

**Comment by xjasonlyu** [comment]
same as #217
