### ISSUE TITLE
[Bug] jellyfin的刮削请求好像没有到服务器端

### ISSUE THREAD

**Issue by KiraHau** [metatube-community/jellyfin-plugin-metatube#265]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

1.2.1

### What OS are you seeing the problem on?

Linux

### Description

直接使用浏览器访问可以获得[GIN]的Get信息，但是使用Jellyfin试图刮削时metatube-server的日志没有任何更新

### MetaTube Server

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/46923871/f93a29e5-178f-447f-b65f-64ab1b116e87)

### Jellyfin/Emby Logs

[21:52:02] [ERR] [103] MediaBrowser.Providers.Manager.ProviderManager: Provider MetaTube failed to retrieve search results
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

### MetaTube Server Logs

[GORM] 2024/01/08 21:51:28 github.com/glebarez/sqlite@v1.10.0/migrator.go:32
[0.097ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_metadata"
[GORM] 2024/01/08 21:51:28 github.com/metatube-community/metatube-sdk-go/engine/engine.go:178
[0.223ms] [rows:0] CREATE TABLE `movie_metadata` (`id` text,`number` text,`title` text,`summary` text,`provider` text,`homepage` text,`director` text,`actors` text[],`thumb_url` text,`big_thumb_url` text,`cover_url` text,`big_cover_url` text,`preview_video_url` text,`preview_video_hls_url` text,`preview_images` text[],`maker` text,`label` text,`series` text,`genres` text[],`score` real,`runtime` integer,`release_date` date,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`))
[GORM] 2024/01/08 21:51:28 github.com/glebarez/sqlite@v1.10.0/migrator.go:32
[0.019ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="actor_metadata"
[GORM] 2024/01/08 21:51:28 github.com/metatube-community/metatube-sdk-go/engine/engine.go:178
[0.138ms] [rows:0] CREATE TABLE `actor_metadata` (`id` text,`name` text,`provider` text,`homepage` text,`summary` text,`hobby` text,`skill` text,`blood_type` text,`cup_size` text,`measurements` text,`nationality` text,`height` integer,`aliases` text[],`images` text[],`birthday` date,`debut_date` date,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`))
[GORM] 2024/01/08 21:51:28 github.com/glebarez/sqlite@v1.10.0/migrator.go:32
[0.020ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_reviews"
[GORM] 2024/01/08 21:51:28 github.com/metatube-community/metatube-sdk-go/engine/engine.go:178
[0.135ms] [rows:0] CREATE TABLE `movie_reviews` (`id` text,`provider` text,`reviews` JSON,PRIMARY KEY (`id`,`provider`))
[GIN] 2024/01/08 - 21:52:09 | 200 |       97.49µs |      | GET      "/"

**Comment by miryuan** [comment]
the same problem

**Comment by JackieWuu** [comment]
> ### Verify steps
> * [ ]  Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
> * [x]  I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
> * [x]  I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related issue.
> 
> ### MetaTube Plugin Version
> 2023.1215.2200.0
> 
> ### MetaTube Server Version
> 1.2.1
> 
> ### What OS are you seeing the problem on?
> Linux
> 
> ### Description
> 直接使用浏览器访问可以获得[GIN]的Get信息，但是使用Jellyfin试图刮削时metatube-server的日志没有任何更新
> 
> ### MetaTube Server
> ![image](https://private-user-images.githubusercontent.com/46923871/294928098-f93a29e5-178f-447f-b65f-64ab1b116e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTAzMDYsIm5iZiI6MTcwNTU5MDAwNiwicGF0aCI6Ii80NjkyMzg3MS8yOTQ5MjgwOTgtZjkzYTI5ZTUtMTc4Zi00NDdmLWI2NWYtNjRhYjFiMTE2ZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE1MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NmUyYzFkOGVlOGFhMjdkNDg2YjRhNGE2YWQwOGI1MjI5YTQ5ZjM4ZTNjZGU1ODhjOTAyMmFiYzU3YzNiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u68I4IrY8c0eGMpPaMxz5RG_eRA2I1I4-5tndOjxY4I)
> 
> ### Jellyfin/Emby Logs
> [21:52:02] [ERR] [103] MediaBrowser.Providers.Manager.ProviderManager: Provider MetaTube failed to retrieve search results System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0. at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) at System.Text.Json.Utf8JsonReader.Read() at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) --- End of inner exception stack trace --- at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex) at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase) at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options) at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken) at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken) at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken) at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken) at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken) at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
> 
> ### MetaTube Server Logs
> [GORM] 2024/01/08 21:51:28 github.com/glebarez/sqlite@v1.10.0/migrator.go:32 [0.097ms] [rows:-] SELECT count(_) FROM sqlite_master WHERE type='table' AND name="movie_metadata" [GORM] 2024/01/08 21:51:28 github.com/metatube-community/metatube-sdk-go/engine/engine.go:178 [0.223ms] [rows:0] CREATE TABLE `movie_metadata` (`id` text,`number` text,`title` text,`summary` text,`provider` text,`homepage` text,`director` text,`actors` text[],`thumb_url` text,`big_thumb_url` text,`cover_url` text,`big_cover_url` text,`preview_video_url` text,`preview_video_hls_url` text,`preview_images` text[],`maker` text,`label` text,`series` text,`genres` text[],`score` real,`runtime` integer,`release_date` date,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`)) [GORM] 2024/01/08 21:51:28 github.com/glebarez/sqlite@v1.10.0/migrator.go:32 [0.019ms] [rows:-] SELECT count(_) FROM sqlite_master WHERE type='table' AND name="actor_metadata" [GORM] 2024/01/08 21:51:28 github.com/metatube-community/metatube-sdk-go/engine/engine.go:178 [0.138ms] [rows:0] CREATE TABLE `actor_metadata` (`id` text,`name` text,`provider` text,`homepage` text,`summary` text,`hobby` text,`skill` text,`blood_type` text,`cup_size` text,`measurements` text,`nationality` text,`height` integer,`aliases` text[],`images` text[],`birthday` date,`debut_date` date,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`)) [GORM] 2024/01/08 21:51:28 github.com/glebarez/sqlite@v1.10.0/migrator.go:32 [0.020ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_reviews" [GORM] 2024/01/08 21:51:28 github.com/metatube-community/metatube-sdk-go/engine/engine.go:178 [0.135ms] [rows:0] CREATE TABLE `movie_reviews` (`id` text,`provider` text,`reviews` JSON,PRIMARY KEY (`id`,`provider`)) [GIN] 2024/01/08 - 21:52:09 | 200 | 97.49µs | | GET "/"
> 
> ### How to Reproduce
> _No response_

我遇到了同样的问题，一开始以为是 metatube 插件或者后端 metatube-server 在设置和安装上的配置不正确造成，最后发现是由于 Jellyfin 在 Unraid 上的权限问题导致的。
Jellyfin 在安装的时候所使用的 PUID 和 GUID 都是 root 权限（0:0），我这两个变量的值改成 99 和 100 之后（为了保险起见我又手动修改了下 appdata 下的 jellyfin 配置文件夹的所属权限：chmow -R 99:100 /mnt/user/appdata/jellyfin）就可以正常刮削了。

**Comment by JackieWuu** [comment]
> the same problem

If you use Unraid too, maybe change the variable PUID & GUID of jellyfin to 99 & 100. I worked it out by that way.

**Comment by lonzoen** [comment]
same problem
jellyfin log:
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/22364270/e777ce98-15fe-481e-94c9-50fcede87459)

**Comment by lonzoen** [comment]
解决了，初步判断是jellyfin使用了clash容器的代理，然后局域网Ip在clash这出了点问题，冻死了，睡觉。

**Comment by miryuan** [comment]
> > the same problem
> 
> If you also use Unraid, consider changing the PUID and PGID variables of Jellyfin to 99 and 100, respectively. I successfully resolved the issue this way. BTW, I also manually executed the command chown `-R 99:100 /mnt/user/appdata/jellyfin to change the file ownership to 99/100` .

群晖的没有办法解决吗
