### ISSUE TITLE
[Bug] emby4.8.3不能刮削

### ISSUE THREAD

**Issue by 907739769** [metatube-community/jellyfin-plugin-metatube#311]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

最新

### MetaTube Server Version

最新

### What OS are you seeing the problem on?

Linux

### Description

emby4.8.3不能刮削

### Jellyfin/Emby Logs

Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:02:28 CST 2024
Framework: .NET 6.0.25
OS/Process: x64/x64
Runtime: system/System.Private.CoreLib.dll
Processor count: 2
Data path: /config
Application path: /system
System.IO.DirectoryNotFoundException: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/run/s6/services/emby-server/希島あいり/ADN-410 希岛爱里/poster.jpg'.
at Emby.Drawing.Skia.SkiaEncoder.GetSKFileStream(String path)
at Emby.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
Source: Emby.Drawing.Skia
TargetSite: SkiaSharp.SKFileStream GetSKFileStream(System.String)
Path: 希島あいり/ADN-410 希岛爱里/poster.jpg
2024-04-11 05:12:30.979 Info Server: http/1.0 Response 404 to host1. Time: 2ms. GET http://host2/emby/Items/1684365/Images/Primary?maxHeight=495&maxWidth=330&tag=1a74c04b64b58d5aa70b79d12e8716d2&quality=90
2024-04-11 05:12:30.982 Error Server: Error processing request
*** Error Report ***
Version: 4.8.3.0
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:02:28 CST 2024
Framework: .NET 6.0.25
OS/Process: x64/x64
Runtime: system/System.Private.CoreLib.dll
Processor count: 2
Data path: /config
Application path: /system
System.IO.DirectoryNotFoundException: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/run/s6/services/emby-server/希島あいり/ADN-415 希島あいり/poster.jpg'.
at Emby.Drawing.Skia.SkiaEncoder.GetSKFileStream(String path)
at Emby.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
Source: Emby.Drawing.Skia
TargetSite: SkiaSharp.SKFileStream GetSKFileStream(System.String)
Path: 希島あいり/ADN-415 希島あいり/poster.jpg

**Comment by 907739769** [comment]
jellyfin能正常刮削

**Comment by 907739769** [comment]
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/27858369/3abd1fb5-2c88-4c0c-817a-5f35ee928e6c)

**Comment by 907739769** [comment]
退回4.8.0.80也是一样

**Comment by 907739769** [comment]
终于找到原因了，把auto movie collection插件卸载就可以了  可能是兼容性问题！！！！搞了好久

**Comment by 907739769** [comment]
搞半天是日语目录的问题
