### ISSUE TITLE
[Bug] emby 4.8.3.0 没请求到服务器

### ISSUE THREAD

**Issue by chaozh00** [metatube-community/jellyfin-plugin-metatube#312]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2024.302.2109.0

### MetaTube Server Version

v1.2.3

### What OS are you seeing the problem on?

Linux

### Description

群晖的套件 emby 4.8.3.0 刮削不了，没发请求到服务器，远端服务器没有对应日志

### Jellyfin/Emby Logs

2024-04-12 19:01:03.551 Info MetaTube.MovieProvider: Search for movie: ABW-096
2024-04-12 19:01:03.771 Error ProviderManager: Error searching
        *** Error Report ***
        Version: 4.8.3.0
        Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology72_{version}_x86_64.spk -noautorunwebapp
        Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #69057 SMP Sat Sep 23 21:48:04 CST 2023
        Framework: .NET 6.0.25
        OS/Process: x64/x64
        Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /var/packages/EmbyServer/var
        Application path: /volume1/@appstore/EmbyServer/system
        System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
         ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
         ---> System.Net.Sockets.SocketException (104): Connection reset by peer
           --- End of inner exception stack trace ---
           at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
           at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
           at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
           at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
           at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
           --- End of inner exception stack trace ---
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
           at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
           at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
           at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
           at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
           at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
           at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
           at Emby.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
           at Emby.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
        Source: System.Net.Http
        TargetSite: Void MoveNext()
        InnerException: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
        Source: System.Net.Sockets
        TargetSite: Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)
           at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
           at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
           at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
           at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
           at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
        InnerException: System.Net.Sockets.SocketException: Connection reset by peer
        Source:
        TargetSite:

**Comment by WUbo5526** [comment]
这几天EMBY一直刮削不了，不知道怎么解决

**Comment by HuangLA** [comment]
一样，我的远端服务器也没有日志

**Comment by maxererer** [comment]
我也一样

**Comment by sheepzacks** [comment]
如果你用的是koyeb的后端，我最近发现koyeb部署的后端能ping通有日志，但是浏览器打不开，所以插件访问不到，我还没找到解决方案，不知道有谁能发现解决方案

**Comment by HuangLA** [comment]
> 如果你用的是koyeb的后端，我最近发现koyeb部署的后端能ping通有日志，但是浏览器打不开，所以插件访问不到，我还没找到解决方案，不知道有谁能发现解决方案

初步怀疑是koyeb的问题，我尝试在自己的vps上用docker部署，刮削成功。

**Comment by sheepzacks** [comment]
我目前找到的解决方案是用dns服务商的反向代理到部署在koyeb的后端，使用也非常稳定

**Comment by maxererer** [comment]
> 我目前找到的解决方案是用dns服务商的反向代理到部署在koyeb的后端，使用也非常稳定

大佬，求教程

**Comment by yoyfirst** [comment]
> 我目前找到的解决方案是用dns服务商的反向代理到部署在koyeb的后端，使用也非常稳定

大佬，同求教程
