### ISSUE TITLE
[Feature] Change Type in PersonInfo initialization from PersonType to PersonKind for upcoming 10.9.0 jellyfin release

### ISSUE THREAD

**Issue by rzalawad** [metatube-community/jellyfin-plugin-metatube#313]
### Description

On Jellyfin 10.9.0, I get this traceback at media scan 
```
[04:07:53] [ERR] Error in MetaTube
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancel
lationToken)
```
In https://github.com/jellyfin/jellyfin/pull/9487, the raw strings were changed to PersonKind Enums.
Since the release of 10.9.0 is coming up (https://jellyfin.org/posts/testing-10.9.0/), this is one change that would need to be implemented for the plugin to work with the newer version.
I just wanted to create this issue to place it under the backlog of 10.9.0 related changes.
I'm not sure how PersonInfo initialization can be made backwards compatible with 10.8.0 (or if its even possible).

**Comment by rzalawad** [comment]
@xjasonlyu To compile with the new codebase, I think we also need to update to .NET 8.0 SDK. I've tried compiling this repo with 6.0 when jellyfin was compiled with 8.0 and it didn't work. However, I'm not sure if there are any ways to make it work or if we'll have to upgrade the SDK

**Comment by rzalawad** [comment]
I have a version of this repo that is up to date with 10.9 related changes (minor sdk + PersonKind change) and works locally on my server.
please lmk if I should submit a PR once the 10.9 is released :)
