### ISSUE TITLE
[Bug] Emby 4.8演员信息nfo不写入演员的MetaTube Id

### ISSUE THREAD

**Issue by noir1216** [metatube-community/jellyfin-plugin-metatube#317]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.512.1925.0

### MetaTube Server Version

1.2.3

### What OS are you seeing the problem on?

群晖

### Description

群晖的套件版Emby 4.8，试了4.8的好几个版本都不行，媒体库高级项已勾选演职人员元数据文件的读写。
![QQ截图20240501190514](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/9cc9b912-0c07-4bd3-870f-334ac8eb59ab)

没有演员MetaTube Id，就没法手动选择头像
![111](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/2770b0bb-6ffe-4fed-8670-000c74f8e242)

### MetaTube Server

同一个MetaTube Server后端，Emby 4.7正常

### Jellyfin/Emby Logs

2024-05-01 18:56:42.478 Info Server: http/1.1 Response 500 to host5. Time: 313ms. GET http://192.168.31.167:8096/emby/Items/RemoteSearch/Image?imageUrl=http://hk.noir9527.shop:8080/v1/images/primary/ARZON/1488404?url=https%3a%2f%2fimg.arzon.jp%2fimage%2f1%2f1488%2f1488404S.jpg&ratio=-1&pos=1&auto=True&quality=90&ProviderName=MetaTube&api_key=x_secret5_x
2024-05-01 18:56:44.216 Info Server: http/1.1 POST http://192.168.31.167:8096/emby/Items/RemoteSearch/Apply/20127?ReplaceAllImages=true&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2024-05-01 18:56:44.218 Info App: Setting provider id's to item 20127-TEK-097 【GW】ふたりは無敵 高橋しょう子 三上悠亜: {"MetaTube":"ARZON:1488404"}
2024-05-01 18:56:44.243 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /var/packages/EmbyServer/target/bin/ffprobe -i file:"/volume2/视频/艾薇/R18/三上悠亚/TEK-097/TEK-097-C.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-05-01 18:56:44.803 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-05-01 18:56:44.805 Info MetaTube.MovieProvider: Get movie info: ARZON:1488404
2024-05-01 18:56:47.131 Info Server: http/1.1 Response 204 to host3. Time: 59ms. POST http://192.168.31.167:8096/emby/Sessions/Playing/Progress
2024-05-01 18:56:48.572 Info Server: http/1.1 Response 204 to host5. Time: 4356ms. POST http://192.168.31.167:8096/emby/Items/RemoteSearch/Apply/20127?ReplaceAllImages=true&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-01 18:56:48.656 Info Server: http/1.1 POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2024-05-01 18:56:48.666 Info App: User policy for YeSi. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-01 18:56:48.667 Info Server: http/1.1 Response 200 to host5. Time: 11ms. POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-01 18:56:48.732 Info HttpClient: GET http://hk.noir9527.shop:8080/v1/images/backdrop/ARZON/1488404?ratio=-1&pos=-1&auto=False&quality=90
2024-05-01 18:56:48.735 Info HttpClient: GET http://hk.noir9527.shop:8080/v1/images/primary/ARZON/1488404?ratio=-1&pos=-1&auto=False&quality=90
2024-05-01 18:56:51.375 Info HttpClient: GET http://hk.noir9527.shop:8080/v1/images/primary/ARZON/1488404?ratio=-1&pos=-1&auto=False&quality=90
2024-05-01 18:56:53.500 Info Server: http/1.1 POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2024-05-01 18:56:53.511 Info Server: http/1.1 POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2024-05-01 18:56:53.525 Info App: User policy for YeSi. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-01 18:56:53.525 Info Server: http/1.1 Response 200 to host5. Time: 26ms. POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-01 18:56:53.526 Info App: User policy for YeSi. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-01 18:56:53.527 Info Server: http/1.1 Response 200 to host5. Time: 16ms. POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-01 18:56:56.383 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.5.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume1/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume1/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Tue May 12 04:54:55 CST 2020
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /volume1/Emby
	Application path: /volume1/@appstore/EmbyServer/system
	System.IO.DirectoryNotFoundException: System.IO.DirectoryNotFoundException: Could not find a part of the path '/volume1/Emby/metadata/people/三/三上悠亜/folder.jpg'.
	   at Emby.Drawing.Skia.SkiaEncoder.GetSKFileStream(String path)
	   at Emby.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Drawing.Skia
	TargetSite: SkiaSharp.SKFileStream GetSKFileStream(System.String)
	Path: /volume1/Emby/metadata/people/三/三上悠亜/folder.jpg
2024-05-01 18:56:56.384 Info Server: http/1.1 Response 404 to host5. Time: 8ms. GET http://192.168.31.167:8096/emby/Items/20306/Images/Primary?tag=dbfb35e1638c80297b7eb44f1e430470&quality=90&maxWidth=320
2024-05-01 18:56:57.100 Info Server: http/1.1 Response 204 to host3. Time: 24ms. POST http://192.168.31.167:8096/emby/Sessions/Playing/Progress
2024-05-01 18:57:04.257 Info Server: http/1.1 POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2024-05-01 18:57:04.259 Info Server: http/1.1 POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2024-05-01 18:57:04.281 Info App: User policy for YeSi. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-01 18:57:04.281 Info App: User policy for YeSi. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-01 18:57:04.281 Info Server: http/1.1 Response 200 to host5. Time: 24ms. POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-01 18:57:04.282 Info Server: http/1.1 Response 200 to host5. Time: 23ms. POST http://192.168.31.167:8096/emby/Items/20127/PlaybackInfo?UserId=ecf5a00dddfd4d2a9ec51e2d9bcaac18&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=14aeb36d-3f74-48c8-9c36-2e08ae986e01&X-Emby-Client-Version=4.8.5.0&X-Emby-Token=x_secret5_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-01 18:57:05.490 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2024-05-01 18:57:47.132 Info Server: http/1.1 Response 204 to host3. Time: 22ms. POST http://192.168.31.167:8096/emby/Sessions/Playing/Progress
2024-05-01 18:57:48.443 Info LibraryMonitor: 三上悠亚 (/volume2/视频/艾薇/R18/三上悠亚) will be refreshed.

**Comment by Moexin** [comment]
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/26740653/6bbee54c-cd55-4030-bc06-75c7cecb3fc9)
看看更新到测试版能不能解决该问题

**Comment by noir1216** [comment]
> ![image](https://private-user-images.githubusercontent.com/26740653/328872725-6bbee54c-cd55-4030-bc06-75c7cecb3fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjg4NjIsIm5iZiI6MTcxNTE2ODU2MiwicGF0aCI6Ii8yNjc0MDY1My8zMjg4NzI3MjUtNmJiZWU1NGMtY2Q1NS00MDMwLWJjMDYtNzVjN2NlY2IzZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDExNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZDcwZDY0YTlmNDA1MTgxMDVjNTM2YWFlYjM1ZTI1MDI0MWJhNDcyMzFjYzNlYjI1YmIwNzIwYTNhZjBiMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQMX0MqdnAwin9DVflkDqpEtz8dOY6zffWtEQ6vhLz8) 看看更新到测试版能不能解决该问题

我手动编辑演员信息是可以写入nfo哦，不管是MetaTube Id还是我自己加的简介都能写入，只是Metatube削刮不能自动写入女优的MetaTube Id，不过我明天还是试试这个测试版看看吧

**Comment by noir1216** [comment]
> ![image](https://private-user-images.githubusercontent.com/26740653/328872725-6bbee54c-cd55-4030-bc06-75c7cecb3fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzE0MDUsIm5iZiI6MTcxNTQzMTEwNSwicGF0aCI6Ii8yNjc0MDY1My8zMjg4NzI3MjUtNmJiZWU1NGMtY2Q1NS00MDMwLWJjMDYtNzVjN2NlY2IzZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEyMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTJhNGQ4ODJmZGM2MWY1YjQ4NTJhZmFjZmQyNjJmMDY4MWM0MDBiZmQxMzlmZGVjOTUyMjViNTk1ZWIyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S_x0fqlvFUkyPa2XtFCLSc9iYemIxQ4Erm3PZL2Oft8) 看看更新到测试版能不能解决该问题

![123](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/824e278d-a3fd-4c53-ae3c-f93721102a99)
试了，还是不行， 最后退回4.7了

**Comment by maxererer** [comment]
> > ![image](https://private-user-images.githubusercontent.com/26740653/328872725-6bbee54c-cd55-4030-bc06-75c7cecb3fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzE0MDUsIm5iZiI6MTcxNTQzMTEwNSwicGF0aCI6Ii8yNjc0MDY1My8zMjg4NzI3MjUtNmJiZWU1NGMtY2Q1NS00MDMwLWJjMDYtNzVjN2NlY2IzZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEyMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTJhNGQ4ODJmZGM2MWY1YjQ4NTJhZmFjZmQyNjJmMDY4MWM0MDBiZmQxMzlmZGVjOTUyMjViNTk1ZWIyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S_x0fqlvFUkyPa2XtFCLSc9iYemIxQ4Erm3PZL2Oft8) 看看更新到测试版能不能解决该问题
> 
> ![123](https://private-user-images.githubusercontent.com/44556349/329781762-824e278d-a3fd-4c53-ae3c-f93721102a99.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk0NjksIm5iZiI6MTcxNTk5OTE2OSwicGF0aCI6Ii80NDU1NjM0OS8zMjk3ODE3NjItODI0ZTI3OGQtYTNmZC00YzUzLWFlM2MtZjkzNzIxMTAyYTk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGU5ODhiYWU1N2QyNjA0YzlhYWU1NjEzNTQzZjVkMWJmZWZiYTI1YjMyNzA2NDI2NjVkYWU4ZTg0ZmEwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qsKw_JQ_ptKqanE09p3r4gs5uI7gy8p_TCugS2z5CWE) 试了，还是不行， 最后退回4.7了

怎么退回的？是重装吗？

**Comment by noir1216** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/26740653/328872725-6bbee54c-cd55-4030-bc06-75c7cecb3fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzE0MDUsIm5iZiI6MTcxNTQzMTEwNSwicGF0aCI6Ii8yNjc0MDY1My8zMjg4NzI3MjUtNmJiZWU1NGMtY2Q1NS00MDMwLWJjMDYtNzVjN2NlY2IzZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEyMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTJhNGQ4ODJmZGM2MWY1YjQ4NTJhZmFjZmQyNjJmMDY4MWM0MDBiZmQxMzlmZGVjOTUyMjViNTk1ZWIyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S_x0fqlvFUkyPa2XtFCLSc9iYemIxQ4Erm3PZL2Oft8) 看看更新到测试版能不能解决该问题
> > 
> > 
> > ![123](https://private-user-images.githubusercontent.com/44556349/329781762-824e278d-a3fd-4c53-ae3c-f93721102a99.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTk0NjksIm5iZiI6MTcxNTk5OTE2OSwicGF0aCI6Ii80NDU1NjM0OS8zMjk3ODE3NjItODI0ZTI3OGQtYTNmZC00YzUzLWFlM2MtZjkzNzIxMTAyYTk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAyMjYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGU5ODhiYWU1N2QyNjA0YzlhYWU1NjEzNTQzZjVkMWJmZWZiYTI1YjMyNzA2NDI2NjVkYWU4ZTg0ZmEwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qsKw_JQ_ptKqanE09p3r4gs5uI7gy8p_TCugS2z5CWE) 试了，还是不行， 最后退回4.7了
> 
> 怎么退回的？是重装吗？

对啊，只能重装了。好在我有之前4.7的设置备份
