### ISSUE TITLE
[Bug] jellyfin 10.90的版本不能自动刮削了

### ISSUE THREAD

**Issue by jeron-lgy** [metatube-community/jellyfin-plugin-metatube#321]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.205.435.0

### MetaTube Server Version

1.23

### What OS are you seeing the problem on?

Linux

### Description

[Bug] jellyfin 10.90的版本不能自动刮削了
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/77041127/2c830d96-e220-4abd-819a-01c90c673407)
计划任务一直失败 ， jellyfin官方和llinuxserver_jellyfin都是这个情况

**Comment by jeron-lgy** [comment]
00:26:09] [INF] [10] Emby.Server.Implementations.Library.LibraryManager: People validation complete
[00:26:09] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: 刷新人员 Completed after 0 minute(s) and 13 seconds
[00:26:12] [ERR] [29] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_MediaTypes(System.String[])'.
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.GenerateTrailersTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.GenerateTrailersTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[00:26:12] [INF] [29] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate Trailers Failed after 0 minute(s) and 0 seconds
[00:26:13] [ERR] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_MediaTypes(System.String[])'.
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.OrganizeMetadataTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[00:26:13] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Organize Metadata Failed after 0 minute(s) and 0 seconds
[00:26:13] [ERR] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_MediaTypes(System.String[])'.
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.GenerateTrailersTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.GenerateTrailersTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[00:26:13] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate Trailers Failed after 0 minute(s) and 0 seconds
[00:26:14] [ERR] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_MediaTypes(System.String[])'.
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.GenerateTrailersTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.MetaTube.ScheduledTasks.GenerateTrailersTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[00:26:14] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate Trailers Failed after 0 minute(s) and 0 seconds
