### ISSUE TITLE
[Bug] AVBASE 刮削不到影片概述

### ISSUE THREAD

**Issue by xyfkthwd** [metatube-community/jellyfin-plugin-metatube#331]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.512.1925.0

### MetaTube Server Version

1.2.3

### What OS are you seeing the problem on?

Linux, Other

### Description

刮削AVBASE源时刮削不到影片概述
其他源有的没有标签有的没有演员，avbase比较全一直把它放首位

### MetaTube Server

docker

### Jellyfin/Emby Logs

2024-05-25 06:14:27.203 Info Server: http/1.1 POST http://host2:8096/emby/Sessions/Capabilities/Full?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=0c1a5dff-089b-479d-ac3c-a61a55199390&X-Emby-Client-Version=4.8.7.0&X-Emby-Token=x_secret2_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
2024-05-25 06:14:27.239 Info Server: http/1.1 Response 204 to host3. Time: 36ms. POST http://host2:8096/emby/Sessions/Capabilities/Full?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=0c1a5dff-089b-479d-ac3c-a61a55199390&X-Emby-Client-Version=4.8.7.0&X-Emby-Token=x_secret2_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-25 06:14:27.406 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2024-05-25 06:16:23.983 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2024-05-25 06:16:26.773 Info Server: http/1.1 POST http://192.168.3.72:8096/emby/Items/41448/PlaybackInfo?UserId=322c9519bf074e23b020974562d688d5&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Linux; Android 14; 23116PN5BC Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
2024-05-25 06:16:26.777 Info App: User policy for xy. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-25 06:16:26.778 Info Server: http/1.1 Response 200 to host1. Time: 5ms. POST http://192.168.3.72:8096/emby/Items/41448/PlaybackInfo?UserId=322c9519bf074e23b020974562d688d5&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-25 06:16:30.455 Info Server: http/1.1 POST http://192.168.3.72:8096/emby/items/metadata/reset?X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Linux; Android 14; 23116PN5BC Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
2024-05-25 06:16:30.637 Info Server: http/1.1 Response 204 to host1. Time: 182ms. POST http://192.168.3.72:8096/emby/items/metadata/reset?X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-25 06:16:30.754 Info Server: http/1.1 POST http://192.168.3.72:8096/emby/Items/41448/PlaybackInfo?UserId=322c9519bf074e23b020974562d688d5&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Linux; Android 14; 23116PN5BC Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
2024-05-25 06:16:30.758 Info App: User policy for xy. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-05-25 06:16:30.759 Info Server: http/1.1 Response 200 to host1. Time: 5ms. POST http://192.168.3.72:8096/emby/Items/41448/PlaybackInfo?UserId=322c9519bf074e23b020974562d688d5&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=160000000&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json
2024-05-25 06:16:37.504 Info Server: http/1.1 POST http://192.168.3.72:8096/emby/Items/RemoteSearch/Movie?X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emby-Client-Version=3.3.56&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn&reqformat=json. UserAgent: Mozilla/5.0 (Linux; Android 14; 23116PN5BC Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
2024-05-25 06:16:37.505 Info MetaTube.MovieProvider: Search for movie: midv-717
2024-05-25 06:16:42.650 Info Server: http/1.1 Response 200 to host1. Time: 5146ms. POST http://192.168.3.72:8096/emby/Items/RemoteSearch/Movie?X-Emby-Client=Emby for Android&X-Emby-Device-Name=23116PN5BC&X-Emby-Device-Id=e9fb6fe9ca83bdcf&X-Emb

### MetaTube Server Logs

2024-05-24 23:53:22.523 Error PortMapper: Error in GetSpecificMappingAsync
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology72_{version}_x86_64.spk
	Operating system: Linux version 4.4.302+ (root@build7) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:02:59 CST 2024
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: InternalServerError
	   at Mono.Nat.Upnp.UpnpNatDevice.GetSpecificMappingAsync(Protocol protocol, Int32 publicPort, CancellationToken cancellationToken)
	   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping, CancellationToken cancellationToken)
	Source: Emby.PortMapper
	TargetSite: Void MoveNext()

**Comment by xjasonlyu** [comment]
是这样子的，因为他本身就不带这些信息。

**Comment by xyfkthwd** [comment]
> 是这样子的，因为他本身就不带这些信息。

那有没有什么办法可以批量刮削结合两个源的元数据？
比如现在avbase有演员信息有标签信息，jav321有概述，现在我想都要这些信息的话只能手动刮削两次

**Comment by xyfkthwd** [comment]
,
