### ISSUE TITLE
[Bug] emby4.8.X用Metatube刮削不到信息，报错

### ISSUE THREAD

**Issue by Mrjind** [metatube-community/jellyfin-plugin-metatube#335]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.512.1925.0

### MetaTube Server Version

4.8.7.0

### Description

1.EmbyServer部署在NAS上，安装的套件版，因为发现MetaTube刮削不成功，看了社区又安装了最新版Emby和Mtatube插件，但是还是显示不成功，懂的大佬麻烦解答下
2.后端部署的是Koyeb，手动在浏览器刮削是能刮到图片的，但是要科学，没有科学不行，koyeb日志也正常，感觉是被墙了，不知道如何解决

### Jellyfin/Emby Logs

2024-05-31 22:49:07.856 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 5ms. GET http://host1:8096/emby/Items/20853/Images/Thumb?maxWidth=320&tag=44af5cadd8d2fe7058e35ded739cedd1&quality=90
2024-05-31 22:49:07.856 Info HttpClient: GET https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1726556?ratio=-1&pos=-1&auto=False&quality=90
2024-05-31 22:49:07.857 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1756531?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:07.857 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 6ms. GET http://host1:8096/emby/Items/20854/Images/Thumb?maxWidth=320&tag=be09942661d5069e9040be7ff2256d90&quality=90
2024-05-31 22:49:07.858 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1726556?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:07.858 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 7ms. GET http://host1:8096/emby/Items/20855/Images/Thumb?maxWidth=320&tag=3cc90176c12a005dcfaf9903a422c716&quality=90
2024-05-31 22:49:07.858 Info HttpClient: GET https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1752911?ratio=-1&pos=-1&auto=False&quality=90
2024-05-31 22:49:07.859 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1752911?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:07.859 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 8ms. GET http://host1:8096/emby/Items/20851/Images/Thumb?maxWidth=320&tag=52f57004930e9d98b4d16f89bc594e29&quality=90
2024-05-31 22:49:07.860 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1724167?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:07.860 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 6ms. GET http://host1:8096/emby/Items/20850/Images/Thumb?maxWidth=320&tag=9d4ca0e2cad696d93497320b682993b3&quality=90
2024-05-31 22:49:07.861 Info HttpClient: GET https://metaube-jindong.koyeb.app:443/v1/images/thumb/JAV321/sqsg00002?ratio=-1&pos=-1&auto=False&quality=90
2024-05-31 22:49:07.862 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/JAV321/sqsg00002?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:07.862 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 2ms. GET http://host1:8096/emby/Items/20847/Images/Thumb?maxWidth=320&tag=d48873e726ade7e571c5c43aa2c1900d&quality=90
2024-05-31 22:49:07.863 Info HttpClient: GET https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1750806?ratio=-1&pos=-1&auto=False&quality=90
2024-05-31 22:49:07.865 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1750806?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:07.865 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 2ms. GET http://host1:8096/emby/Items/20852/Images/Thumb?maxWidth=320&tag=6a443b51127377cb661e5bc788986a12&quality=90
2024-05-31 22:49:08.038 Info HttpClient: GET https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1742517?ratio=-1&pos=-1&auto=False&quality=90
2024-05-31 22:49:08.040 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /var/packages/EmbyServer/var -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /var/packages/EmbyServer/var/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology7_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.180+ (root@build2) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Feb 10 16:34:59 CST 2023
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/packages/EmbyServer/var
	Application path: /volume1/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://metaube-jindong.koyeb.app:443/v1/images/thumb/ARZON/1742517?ratio=-1&pos=-1&auto=False&quality=90 due to a previous timeout.
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Int64[] generatedFromItemIds, IDirectoryService directoryService, Boolean updateImageCache, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, CancellationToken cancellationToken)
	   at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options, CancellationToken cancellationToken)
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2024-05-31 22:49:08.040 Info Server: http/1.1 Response 500 to emby_remote_ip. Time: 3ms. GET http://host1:8096/emby/Items/20849/Images/Thumb?maxWidth=320&tag=1e3c35bc9ec2c80aaf347d2bcdb33bae&quality=90
![图片1](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/128960599/2cb9a684-9c81-4cf3-ab92-c175d3e56755)

**Comment by Mrjind** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Mrjind** [comment]
> 应该是网络或者政权问题，日志里没有出来具体的原因。

请问我该如何排查呢？关于日志里显示超时的地址，翻墙是能访问的，之前是不需要翻墙也可以

**Comment by noir1216** [comment]
后端域名能联通的号，会返回例如下面的数据：
{"data":{"app":"metatube","commit":"6afd043","version":"1.2.3"}}

**Comment by lostars** [comment]
我也遇到了类似问题，emby 4.8.8.0，发现1.2.4后端出现了大量的broken pipe，只有封面图无法加载，其他数据正常刮削。手动修改封面可以搜索到其他视频截图，无法加载位于第一个的封面

**Comment by Mrjind** [comment]
> 我也遇到了类似的问题，emby 4.8.8.0，发现1.2.4清单出现了大量的破管，只有封面图无法加载，其他数据正常刮削。手动修改封面可以搜索到其他视频截图，无法加载位于第一个封面。手动刮削换几个来源发现应该是来源问题，默认的获取顺序，封面加载可能会失败，手动刮削选择数据就好了。

请问你用的后端是走代理的吗？

**Comment by Mrjind** [comment]
> 名单域名能联通的话，会返回例如下面的数据： {"data":{"app":"metatube","commit":"6afd043","version":"1.2.3"}}

是的，在使用代理的情况下，能正常返回数据，不使用代理就不行了，这种情况有什么解决方法呢，旁路由吗？

**Comment by noir1216** [comment]
> > 名单域名能联通的话，会返回例如下面的数据： {"data":{"app":"metatube","commit":"6afd043","version":"1.2.3"}}
> 
> 是的，在使用代理的情况下，能正常返回数据，不使用代理就不行了，这种情况有什么解决方法呢，旁路由吗？

旁路由可以解决，不过我还是建议你优先koyeb删机后换个域名重新生成试试

**Comment by QZQ-QSQ** [comment]
同样的版本，同样的问题。

**Comment by ssyoua** [comment]
我在自己的服务器上建了后端，emby4.8.8能连通刮削，说明插件没问题。但用emby无法联通kobye域名，后端无信息显示，网页打开koyeb域名又能返回信息，且后端有信息显示，说明是没有被墙的，搞不懂了

**Comment by Jang-Ha-ri** [comment]
> 我也遇到了类似的问题，emby 4.8.8.0，发现1.2.4清单出现了大量的破管，只有封面图无法加载，其他数据正常刮削。手动修改封面可以搜索到其他视频截图，无法加载位于第一个封面。手动刮削换几个来源发现应该是来源问题，默认的获取顺序，封面加载可能会失败，手动刮削选择数据就好了。

我的jellyfin10.8.13也有同样的问题，自动刮削仅有视频截图作为封面，其他一切正常。手动修改图片时，所有搜出来的候选图都无法预览，不过可以下载来用，虽然基本上都是视频截图。
![捕获2](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/123641077/ec41e09b-95d2-4f50-bf86-c6201ba20c4f)

**Comment by Mrjind** [comment]
我刚解决，确实就是后端被墙了，用旁路由搭科学上网环境，在NAS里指定

**Comment by QZQ-QSQ** [comment]
> 我刚解决，确实就是后端被墙了，用旁路由搭科学上网环境，在NAS里指定

我使用部署在美国的后端也是破图。
