### ISSUE TITLE
PC本地部署后台，全局代理，刮削请求失败[Bug] 

### ISSUE THREAD

**Issue by zhangtiezhi** [metatube-community/jellyfin-plugin-metatube#341]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024610202

### MetaTube Server Version

1.2.4

### What OS are you seeing the problem on?

Windows

### Description

因 koyeb 部署被墙之后，采用办公室PC本地部署，开全局代理，内网穿透支持NAS。大概在一星期之前发现刮削失效了，请求连接失败。

### MetaTube Server

metatube-server-windows-amd64-v3 直接双击运行的。

### Jellyfin/Emby Logs

[10:34:46] [INF] [27] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /var/packages/Jellyfin/target/bin/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/volume1/mydata/jellyfin/骑兵/SSIS-144-C/SSIS-144-C.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[10:34:47] [INF] [27] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: SSIS-144-C
[10:35:20] [WRN] [30] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 111.207.189.210 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[10:35:20] [INF] [30] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 111.207.189.210 closed
[10:35:21] [INF] [32] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Get movie info: ARZON:1633790
[10:35:43] [ERR] [32] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube
System.Exception: API request error: 500 (Get "https://www.arzon.jp/item_1633790.html": dial tcp 210.134.56.83:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[10:35:43] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /var/packages/Jellyfin/target/bin/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/volume1/mydata/jellyfin/骑兵/SSIS-604-C/SSIS-604-C.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[10:35:43] [INF] [32] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: SSIS-604-C
[10:36:25] [ERR] [3] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube
System.Exception: API request error: 404 (info not found)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[10:36:25] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /var/packages/Jellyfin/target/bin/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/volume1/mydata/jellyfin/骑兵/SSNI-826-C/SSNI-826-C.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[10:36:26] [INF] [32] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: SSNI-826-C
[10:37:08] [ERR] [33] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube

### MetaTube Server Logs

{"level":"info","ts":1718082954.7914796,"caller":"engine/movie.go:137","msg":"Search keyword SSNI-826: AIRAV(0s): invalid keyword MYWIFE(0s): invalid id H4610(0s): invalid id MURAMURA(0s): invalid id 1Pondo(506.7µs): invalid id Getchu(516.6µs): invalid id Pcolle(516.6µs): invalid id TOKYO-HOT(516.6µs): invalid keyword HEYZO(516.6µs): invalid id PACOPACOMAMA(516.6µs): invalid id C0930(516.6µs): invalid id KIN8(516.6µs): invalid id HeyDouga(516.6µs): invalid id Caribbeancom(516.6µs): invalid id H0930(516.6µs): invalid id Gcolle(516.6µs): invalid id XXX-AV(516.6µs): invalid id fc2hub(516.6µs): invalid keyword CaribbeancomPR(516.6µs): invalid id 10musume(516.6µs): invalid id FC2(516.6µs): invalid id MGS(301.2291ms): Forbidden DAHLIA(735.6851ms): <nil> AVE(1.9723201s): <nil> SOD(2.512283s): <nil> JAV321(10.0149008s): Post \"https://www.jav321.com/search\": context deadline exceeded (Client.Timeout exceeded while awaiting headers) ARZON(11.1884785s): Get \"https://www.arzon.jp/itemlist.html?&q=SSNI-826&t=all&m=all&s=all&mkt=all&disp=30&sort=-udate\": net/http: TLS handshake timeout JavBus(20.5646513s): <nil> FALENO(21.0678481s): Get \"https://faleno.jp/top/?s=ssni826\": dial tcp 104.244.43.57:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. DUGA(21.0678481s): Get \"https://duga.jp/search/=/q=SSNI-826/\": dial tcp 108.160.167.158:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. AVBASE(21.0678481s): Get \"https://www.avbase.net/\": dial tcp 151.101.90.132:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. FANZA(42.109318s): Get \"https://www.dmm.co.jp/search/=/searchstr=ssni826/limit=120/sort=date/\": dial tcp 3.165.96.52:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
[GORM] 2024/06/11 13:15:54 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
[0.000ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "SSNI-826" COLLATE NOCASE OR id = "SSNI-826" COLLATE NOCASE
[GIN] 2024/06/11 - 13:15:54 | 404 |   42.1219652s |  106.120.14.196 | GET      "/v1/movies/search?q=SSNI-826-C&provider=&fallback=True"

**Comment by zhangtiezhi** [comment]
今天升级后好像又好了。
