### ISSUE TITLE
[Bug] 搜索不到任何结果。之前同插件版本成功刮到过

### ISSUE THREAD

**Issue by suede299** [metatube-community/jellyfin-plugin-metatube#401]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

1.2.7

### What OS are you seeing the problem on?

Linux

### Description

手动搜索不到任何结果，很快就返回 未找到符合您搜索条件的项目。
距上次成功刮到，更新过nas系统、emby版本。
刚页打开后端地址能看到版本号(无科学)
尝试过取消Enable real actor names和Enable movie provider filter，因为看到有人说avbase导致的搜不到。但问题依旧，同样的日志。
设备网络没问题，因为下载任务都在进行。
看上去就是连不上后端。因为我去掉插件配置里的Token。都依然得到相同的日志。

### Jellyfin/Emby Logs

2024-09-29 20:55:09.737 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2024-09-29 20:55:15.492 Info Server: http/1.1 POST http://10.138.1.178:8096/emby/Items/17041/PlaybackInfo?UserId=1071357ad6b7458f8399f4817628e5ff&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=200000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=164ac16e-a3a8-4cd9-bcdb-f9db61620e35&X-Emby-Client-Version=4.8.9.0&X-Emby-Token=x_secret3_x&X-Emby-Language=zh-cn&reqformat=json. Source Ip: host3, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
2024-09-29 20:55:15.495 Info App: User policy for Suede0. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
2024-09-29 20:55:15.599 Info Server: http/1.1 Response 200 to host3. Time: 107ms. POST http://10.138.1.178:8096/emby/Items/17041/PlaybackInfo?UserId=1071357ad6b7458f8399f4817628e5ff&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=200000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=164ac16e-a3a8-4cd9-bcdb-f9db61620e35&X-Emby-Client-Version=4.8.9.0&X-Emby-Token=x_secret3_x&X-Emby-Language=zh-cn&reqformat=json
2024-09-29 20:55:21.868 Info Server: http/1.1 POST http://10.138.1.178:8096/emby/Items/RemoteSearch/Movie?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=164ac16e-a3a8-4cd9-bcdb-f9db61620e35&X-Emby-Client-Version=4.8.9.0&X-Emby-Token=x_secret3_x&X-Emby-Language=zh-cn&reqformat=json. Source Ip: host3, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
2024-09-29 20:55:21.869 Info MetaTube.MovieProvider: Search for movie: ADN-554
2024-09-29 20:55:23.508 Error ProviderManager: Error searching
	*** Error Report ***
	Version: 4.8.9.0
	Command line: /volume1/.@plugins/AppCentral/emby-server/system/EmbyServer.dll -programdata /home/emby -ffdetect /usr/local/AppCentral/emby-server/bin/ffdetect -ffmpeg /usr/local/AppCentral/emby-server/bin/ffmpeg -ffprobe /usr/local/AppCentral/emby-server/bin/ffprobe -defaultdirectory /volume1/Public -updatepackage emby-server-asustor_{version}_x86-64.apk
	Operating system: Linux version 5.13.x (root@sw1-dailybuild) (x86_64-asustor_x64_g3_2020.12.24-linux-gnu-gcc (crosstool-NG 1.24.0) 7.4.0, GNU ld (crosstool-NG 1.24.0) 2
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: volume1/.@plugins/AppCentral/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /home/emby
	Application path: /volume1/.@plugins/AppCentral/emby-server/system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
	 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
	 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
	   --- End of inner exception stack trace ---
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
	   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
	   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
	Source: System.Net.Sockets
	TargetSite: Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
	   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
	   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	InnerException: System.Net.Sockets.SocketException: Connection reset by peer
	Source: 
	TargetSite: 
	
2024-09-29 20:55:23.508 Info Server: http/1.1 Response 200 to host3. Time: 1640ms. POST http://10.138.1.178:8096/emby/Items/RemoteSearch/Movie?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=164ac16e-a3a8-4cd9-bcdb-f9db61620e35&X-Emby-Client-Version=4.8.9.0&X-Emby-Token=x_secret3_x&X-Emby-Language=zh-cn&reqformat=json

### MetaTube Server Logs

Instance created. Preparing to start...
Instance is starting. Propagating network configuration...
[GORM] 2024/09/29 13:09:15 github.com/glebarez/sqlite@v1.11.0/migrator.go:32
[0.328ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_metadata"
[GORM] 2024/09/29 13:09:15 github.com/metatube-community/metatube-sdk-go/engine/database.go:21
[0.736ms] [rows:0] CREATE TABLE `movie_metadata` (`id` text,`number` text,`title` text,`summary` text,`provider` text,`homepage` text,`director` text,`actors` text[],`thumb_url` text,`big_thumb_url` text,`cover_url` text,`big_cover_url` text,`preview_video_url` text,`preview_video_hls_url` text,`preview_images` text[],`maker` text,`label` text,`series` text,`genres` text[],`score` real,`runtime` integer,`release_date` date,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`))
[GORM] 2024/09/29 13:09:15 github.com/glebarez/sqlite@v1.11.0/migrator.go:32
[0.052ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="actor_metadata"
[GORM] 2024/09/29 13:09:15 github.com/metatube-community/metatube-sdk-go/engine/database.go:21
[0.270ms] [rows:0] CREATE TABLE `actor_metadata` (`id` text,`name` text,`provider` text,`homepage` text,`summary` text,`hobby` text,`skill` text,`blood_type` text,`cup_size` text,`measurements` text,`nationality` text,`height` integer,`aliases` text[],`images` text[],`birthday` date,`debut_date` date,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`))
[GORM] 2024/09/29 13:09:15 github.com/glebarez/sqlite@v1.11.0/migrator.go:32
[0.047ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_reviews"
[GORM] 2024/09/29 13:09:15 github.com/metatube-community/metatube-sdk-go/engine/database.go:21
[0.204ms] [rows:0] CREATE TABLE `movie_reviews` (`id` text,`provider` text,`reviews` JSON,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`,`provider`))
lib/jpegli/decode_marker.cc:504: Did not find SOI marker.
Instance is healthy. All health checks are passing.
[GIN] 2024/09/29 - 13:10:38 | 200 |      285.13µs | 103.127.218.197 | GET      "/"
[GIN] 2024/09/29 - 13:46:32 | 200 |       98.85µs | 103.127.218.197 | GET      "/"
[GIN] 2024/09/29 - 13:55:41 | 200 |       66.21µs | 103.127.218.197 | GET      "/"
[GIN] 2024/09/29 - 13:59:24 | 200 |       68.78µs |  118.114.93.163 | GET      "/"

**Comment by xjasonlyu** [comment]
网络问题，需要保证网络连接正常。

**Comment by suede299** [comment]
> 网络问题，需要保证网络连接正常。

我担心是emby网络连接有问题。还专门去试了下。
![image](https://github.com/user-attachments/assets/0d27991a-4447-41c9-922b-667273c1fe72)
movieDb插件搜一般电影的能搜到。是不是说明网络没问题啊。

**Comment by xjasonlyu** [comment]
后端的网络，而且moviedb能连接不代表后端能够正常连接的。
