### ISSUE TITLE
把服务端代理到二级路径的问题

### ISSUE THREAD

**Issue by iamckun** [metatube-community/jellyfin-plugin-metatube#418]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

1.2.6

### What OS are you seeing the problem on?

Linux

### Description

使用二级路径无法调用api，我填写的是
https://example.com/metatube
https://example.com/metatube/
比如我手动调用接口如：
https://example.com/metatube/v1/movies/AVE/20833?lazy=True
是正常的响应的，问题应该是在插件这里希望可以适配代理

### Jellyfin/Emby Logs

2024-10-28 10:24:05.830 Info MetaTube.MovieProvider: Search for movie: XVN コスプレ痴女 患者のチンコ触診するナース 立花里子
2024-10-28 10:24:05.832 Error App: Error in MetaTube
*** Error Report ***
Version: 4.8.10.0
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #64570 SMP Tue Jun 13 21:39:55 CST 2023
Framework: .NET 6.0.31
OS/Process: x64/x64
Runtime: system/System.Private.CoreLib.dll
Processor count: 8
Data path: /config
Application path: /system
System.Text.Json.JsonException: System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
at System.Text.Json.Utf8JsonReader.Read()
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
--- End of inner exception stack trace ---
at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IRemoteMetadataProvider`2[] providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
Source: System.Text.Json
TargetSite: Void ReThrowWithPath(System.Text.Json.ReadStack ByRef, System.Text.Json.JsonReaderException)
InnerException: System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
Source: System.Text.Json
TargetSite: Void ThrowJsonReaderException(System.Text.Json.Utf8JsonReader ByRef, System.Text.Json.ExceptionResource, Byte, System.ReadOnlySpan`1[System.Byte])
at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
at System.Text.Json.Utf8JsonReader.Read()
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

### MetaTube Server Logs

无

**Comment by xjasonlyu** [comment]
是的，插件不可以使用二级路径

**Comment by iamckun** [comment]
> 是的，插件不可以使用二级路径

@xjasonlyu 可以支持一下吗

**Comment by xjasonlyu** [comment]
感觉不需要特别支持，使用virtual host就可以解决了。

**Comment by iamckun** [comment]
使用太多的域名会有一些额外的支出，二级目录是个非常不错的体验。

**Comment by iamckun** [comment]
> > 使用太多的域名会有一些额外的支出，二级目录是个非常不错的体验。
> 
> 解析个新的二级域名1分钟都不需要，这都不愿做？让作者来？

你不说话没人把你当哑巴，不会说话就闭嘴，你咋不说解析个范域名一分钟都不要呢

**Comment by bobo-link** [comment]
https://github.com/metatube-community/jellyfin-plugin-metatube/blob/main/Jellyfin.Plugin.MetaTube/ApiClient.cs 
![image](https://github.com/user-attachments/assets/ac3ea44b-c072-4d13-a891-648b196f5419)
![image](https://github.com/user-attachments/assets/e9dd0f00-b4d5-4940-bd25-27f1185fa699)
这个文件中 Path 那里代码改一下，这个函数会覆盖传入uil 中 host 后的 path 的。

**Comment by bobo-link** [comment]
https://github.com/metatube-community/jellyfin-plugin-metatube/blob/main/Jellyfin.Plugin.MetaTube/ApiClient.cs
![image](https://github.com/user-attachments/assets/f01d40a3-b480-44f0-8708-c478f62d62e8)
![image](https://github.com/user-attachments/assets/5010a03c-ce99-4682-a91d-c64950d51e2f)
修改该文件的目标代码，[Build from source](https://metatube-community.github.io/wiki/build-from-source/) 后使用dll文件  [替换服务器上插件dll文件](https://jellyfin.org/docs/general/server/plugins/#manual) 就行。
jellyfin 10.9 以下的可以用这个 [metatube.2024.205.435--mirror-SUB PATH SUPPORT](https://gitee.com/OPs_goy/metatube.2024.205.435--mirror/blob/dist/manifest.json)
