### ISSUE TITLE
[Bug] plugin does not work properly under Jellyfin 10.10.0.

### ISSUE THREAD

**Issue by PlutoNameless** [metatube-community/jellyfin-plugin-metatube#425]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.10-31.200.0

### MetaTube Server Version

1.2.7

### Description

 Jellyfin 10.10.0.

The cover cannot be retrieved. When selecting the image manually, only the image item appears without a preview.
Clicking to open the image requests the following link:
http://127.0.0.1:8080/v1/images/primary/ARZON/1766478?url=https%3a%2f%2fimg.arzon.jp%2fimage%2f1%2f1766%2f1766478P-03.jpg&ratio=-1&pos=-1&auto=False&quality=90

The browser shows the error "ERR_CONNECTION_REFUSED."

When the browser requests this link:
https://img.arzon.jp/image/1/1759/1759838P-03.jpg,
the webpage displays "Forbidden. You don't have permission to access /image/1/1759/1759838P-04.jpg on this server."

I tried switching to Japanese, American, and Hong Kong nodes, but it was ineffective.

![image](https://github.com/user-attachments/assets/8163945c-9566-40a8-bdf2-74f3262ecad3)

### Jellyfin/Emby Logs

[2024-11-04 14:04:15.574 +08:00] [ERR] [17] MediaBrowser.Providers.Manager.ProviderManager: "MovieImageProvider" failed in GetImageInfos for type "Movie" at "/volume1/video/jav/SONE-065/SONE-065-FHD.mp4"
System.Exception: API request error: 500 (Get "https://www.arzon.jp/item_1759838.html": read tcp 172.17.0.4:52574->198.18.0.114:443: read: connection reset by peer)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)

### MetaTube Server Logs

[23.504ms] [rows:1] INSERT INTO `movie_metadata` (`id`,`number`,`title`,`summary`,`provider`,`homepage`,`director`,`actors`,`thumb_url`,`big_thumb_url`,`cover_url`,`big_cover_url`,`preview_video_url`,`preview_video_hls_url`,`preview_images`,`maker`,`label`,`series`,`genres`,`score`,`runtime`,`release_date`,`created_at`,`updated_at`) VALUES ("1759838","SONE-065","激イキ186回！ 痙攣4602回！ イキ潮3200cc！ エロめっちゃ可愛い三田真鈴 エロス覚醒 はじめての大大大・痙・攣スペシャル","エロめっちゃ可愛い三田真鈴のエロスが大覚醒。今までのような“甘ったるいSEX”は、本日をもって終了。濃厚なベロキス性交や壊れてしまいそうな玩具＆ピストン責めで彼女の美ボディがイキ跳ねる。","ARZON","https://www.arzon.jp/item_1759838.html","苺原","{""三田真鈴""}","https://img.arzon.jp/image/1/1759/1759838S.jpg","","https://img.arzon.jp/image/1/1759/1759838L.jpg","","","","{""https://img.arzon.jp/image/1/1759/1759838P-01.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-02.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-03.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-04.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-05.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-06.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-07.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-08.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-09.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-10.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-11.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-12.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-13.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-14.jpg"",""https://img.arzon.jp/image/1/1759/1759838P-15.jpg""}","Ｓ１（エスワン　ナンバーワンスタイル）","Ｓ１　ＮＯ．１　ＳＴＹＬＥ","","{}",0,120,"2024-02-13 00:00:00","2024-11-04 06:12:11.356","2024-11-04 06:12:11.356") ON CONFLICT (`id`,`provider`) DO UPDATE SET `updated_at`="2024-11-04 06:12:11.356",`number`=`excluded`.`number`,`title`=`excluded`.`title`,`summary`=`excluded`.`summary`,`homepage`=`excluded`.`homepage`,`director`=`excluded`.`director`,`actors`=`excluded`.`actors`,`thumb_url`=`excluded`.`thumb_url`,`big_thumb_url`=`excluded`.`big_thumb_url`,`cover_url`=`excluded`.`cover_url`,`big_cover_url`=`excluded`.`big_cover_url`,`preview_video_url`=`excluded`.`preview_video_url`,`preview_video_hls_url`=`excluded`.`preview_video_hls_url`,`preview_images`=`excluded`.`preview_images`,`maker`=`excluded`.`maker`,`label`=`excluded`.`label`,`series`=`excluded`.`series`,`genres`=`excluded`.`genres`,`score`=`excluded`.`score`,`runtime`=`excluded`.`runtime`,`release_date`=`excluded`.`release_date`

[GIN] 2024/11/04 - 05:46:33 \| 200 \| 19.376474241s \|      172.17.0.1 \| GET      "/v1/movies/search?q=SONE-065&provider=&fallback=True"

[0.442ms] [rows:2] SELECT * FROM `movie_metadata` WHERE number = "SONE-065" COLLATE NOCASE OR id = "SONE-065" COLLATE NOCASE

[ENGINE] 2024/11/04 05:46:33 github.com/metatube-community/metatube-sdk-go/engine/movie.go:142: Search keyword SONE-065: CaribbeancomPR(31.103µs):<invalid id> \| TOKYO-HOT(60.443µs):<invalid keyword> \| 1Pondo(63.774µs):<invalid id> \| H4610(93.804µs):<invalid id> \| MYWIFE(81.963µs):<invalid id> \| HeyDouga(92.091µs):<invalid id> \| HEYZO(121.654µs):<invalid id> \| 10musume(98.058µs):<invalid id> \| PACOPACOMAMA(106.046µs):<invalid id> \| C0930(131.422µs):<invalid id> \| XXX-AV(152.029µs):<invalid id> \| MURAMURA(169.508µs):<invalid id> \| Caribbeancom(175.519µs):<invalid id> \| fc2hub(209.763µs):<invalid keyword> \| FC2(278.72µs):<invalid id> \| Gcolle(294.884µs):<invalid id> \| AIRAV(318.855µs):<invalid keyword> \| KIN8(305.753µs):<invalid id> \| Getchu(329.03µs):<invalid id> \| Pcolle(333.251µs):<invalid id> \| H0930(337.525µs):<invalid id> \| MGS(76.308298ms):<Forbidden> \| SOD(142.719833ms):<Forbidden> \| DUGA(151.131386ms):<Service Unavailable> \| JAV321(365.60931ms):<no error> \| JavBus(624.681823ms):<no error> \| FALENO(1.063078639s):<no error> \| AVE(1.145404322s):<no error> \| AVBASE(1.49559059s):<no error> \| FANZA(2.644387688s):<not-available-in-your-region> \| ARZON(13.810894524s):<no error> \| DAHLIA(19.375692901s):<no error>

**Comment by Topbcy** [comment]
switch to avbase, your network ARZON latency higher than other one.

**Comment by liya1413** [comment]
我也是一样，能削挂到文本，不显示图片

**Comment by PlutoNameless** [comment]
> switch to avbase, your network ARZON latency higher than other one.
A new error occurred after changing the source, and I have rebuilt the media library


[21:18:58] [ERR] [36] MediaBrowser.Providers.Manager.ProviderManager: MovieImageProvider failed in GetImageInfos for type Movie at /volume1/video/jav/SSIS-846/SSIS-846-C.mp4
System.Exception: API request error: 404 (provider not found)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, Boolean lazy, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetMovieInfoAsync(String provider, String id, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)

**Comment by xjasonlyu** [comment]
Try to use the `metatube-server:dev` image, as some patches are not included in the `v1.2.7` image but have been applied to the main branch.

**Comment by PlutoNameless** [comment]
> Try to use the `metatube-server:dev` image, as some patches are not included in the `v1.2.7` image but have been applied to the main branch.

I'm glad you responded, but after I used the dev branch of this docker source, the problem remained; I also found that the last update on this dev branch was 16 days ago. Does this include the latest fix for this issue?

https://registry.hub.docker.com/r/metatube/metatube-server/tags

One new change is that I discovered the 10.10.1 update for jellyfin, which I updated before this attempt, but it didn't help me.

**Comment by PlutoNameless** [comment]
I found the cause of the issue. Previously, the Server address in the Metatube plugin was set to 127.0.0.1, but this stopped working with Jellyfin version 10.10.0. Once I changed it to the correct internal network address, the issue was resolved.
