### ISSUE TITLE
[Bug] Jellyfin 10.10.0 无法正常刮削到电影文本信息

### ISSUE THREAD

**Issue by Yiomo** [metatube-community/jellyfin-plugin-metatube#428]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.1031.200.0

### MetaTube Server Version

1.2.7

### What OS are you seeing the problem on?

Other

### Description

有的影片刮削不到文本信息，能够正确刮削影片的ID，查看日志错误未“System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'value')”

### Jellyfin/Emby Logs

```
[17:37:39] [INF] [17] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: SMOK-006
[17:38:43] [INF] [37] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item da7e5f35-c3f2-13cb-251d-af954b66d778-SMOK-006: {"MetaTube": "FANZA:smok006"}
[17:38:43] [INF] [37] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /var/packages/Jellyfin/target/bin/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/volume1/Private/VIDEO/JP/SMOK-006.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[17:38:43] [INF] [25] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Get movie info: FANZA:smok006
[17:38:43] [ERR] [25] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube
System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'value')
   at System.ArgumentException.ThrowNullOrWhiteSpaceException(String argument, String paramName)
   at MediaBrowser.Model.Entities.ProviderIdsExtensions.SetProviderId(IHasProviderIds instance, String name, String value)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[17:39:09] [INF] [25] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: LULU-340
[17:39:25] [INF] [98] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 938e66d4-9d6b-e35d-052d-feccdfd9f88e-LULU-340: {"MetaTube": "AVBASE:lunatics%3ALULU-340"}
[17:39:25] [INF] [98] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /var/packages/Jellyfin/target/bin/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/volume1/Private/VIDEO/JP/LULU-340.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[17:39:25] [INF] [25] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Get movie info: AVBASE:lunatics:LULU-340
[17:39:25] [ERR] [98] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube
System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'value')
   at System.ArgumentException.ThrowNullOrWhiteSpaceException(String argument, String paramName)
   at MediaBrowser.Model.Entities.ProviderIdsExtensions.SetProviderId(IHasProviderIds instance, String name, String value)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
### MetaTube Server Logs
```
[GORM] 2024/11/05 09:38:43 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[4.340ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "FANZA" AND id = "smok006" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:38:43 | 200 | 4.651676ms | 192.168.10.203 | GET "/v1/movies/FANZA/smok006?lazy=True"
[GORM] 2024/11/05 09:38:43 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[4.045ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "FANZA" AND id = "smok006" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:38:43 | 200 | 4.307518ms | 192.168.10.203 | GET "/v1/movies/FANZA/smok006?lazy=True"
[GORM] 2024/11/05 09:38:43 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[4.034ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "FANZA" AND id = "smok006" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:38:46 | 200 | 2.513135548s | 192.168.10.203 | GET "/v1/images/primary/FANZA/smok006?ratio=-1&pos=-1&auto=False&quality=90"
[GORM] 2024/11/05 09:38:46 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[4.174ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "FANZA" AND id = "smok006" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:38:46 | 200 | 483.10932ms | 192.168.10.203 | GET "/v1/images/thumb/FANZA/smok006?ratio=-1&pos=-1&auto=False&quality=90"
[GORM] 2024/11/05 09:38:46 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[1.264ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "FANZA" AND id = "smok006" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:38:47 | 200 | 427.026715ms | 192.168.10.203 | GET "/v1/images/backdrop/FANZA/smok006?ratio=-1&pos=-1&auto=False&quality=90"
[ENGINE] 2024/11/05 09:39:19 github.com/metatube-community/metatube-sdk-go/engine/movie.go:142: Search keyword LULU-340: TOKYO-HOT(64.457µs):<invalid keyword> | Pcolle(80.789µs):<invalid id> | C0930(86.331µs):<invalid id> | CaribbeancomPR(104.998µs):<invalid id> | HEYZO(170.912µs):<invalid id> | H4610(197.745µs):<invalid id> | Caribbeancom(234.494µs):<invalid id> | KIN8(279.118µs):<invalid id> | fc2hub(321.409µs):<invalid keyword> | 10musume(331.033µs):<invalid id> | FC2(347.658µs):<invalid id> | Getchu(387.908µs):<invalid id> | PACOPACOMAMA(401.032µs):<invalid id> | HeyDouga(380.615µs):<invalid id> | MYWIFE(448.281µs):<invalid id> | Gcolle(469.572µs):<invalid id> | MURAMURA(505.446µs):<invalid id> | 1Pondo(524.404µs):<invalid id> | XXX-AV(529.07µs):<invalid id> | H0930(603.735µs):<invalid id> | AIRAV(697.066µs):<invalid keyword> | MGS(961.351137ms):<Forbidden> | AVBASE(971.476677ms):<no error> | SOD(1.051823305s):<Forbidden> | JAV321(1.184670085s):<no error> | JavBus(1.333803419s):<no error> | DUGA(1.710778753s):<no error> | FALENO(1.798908604s):<no error> | FANZA(2.638486686s):<not-available-in-your-region> | ARZON(2.754243974s):<no error> | AVE(3.280694468s):<no error> | DAHLIA(10.003497351s):<Get "https://dahlia-av.jp/?s=lulu340": net/http: TLS handshake timeout>
[GORM] 2024/11/05 09:39:19 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
[6.549ms] [rows:2] SELECT * FROM `movie_metadata` WHERE number = "LULU-340" COLLATE NOCASE OR id = "LULU-340" COLLATE NOCASE
[GIN] 2024/11/05 - 09:39:19 | 200 | 10.010551134s | 192.168.10.203 | GET "/v1/movies/search?q=LULU-340&provider=&fallback=True"
[GIN] 2024/11/05 - 09:39:20 | 200 | 535.5841ms | 192.168.10.23 | GET "/v1/images/primary/JavBus/LULU-340?url=https%3a%2f%2fwww.javbus.com%2fpics%2fthumb%2fauxm.jpg&ratio=-1&pos=1&auto=True&quality=90"
[GIN] 2024/11/05 - 09:39:20 | 200 | 642.444318ms | 192.168.10.23 | GET "/v1/images/primary/AVBASE/lunatics:LULU-340?url=https%3a%2f%2fpics.dmm.co.jp%2fdigital%2fvideo%2flulu00340%2flulu00340ps.jpg&ratio=-1&pos=1&auto=True&quality=90"
[GIN] 2024/11/05 - 09:39:20 | 200 | 1.038704466s | 192.168.10.23 | GET "/v1/images/primary/ARZON/1795725?url=https%3a%2f%2fimg.arzon.jp%2fimage%2f1%2f1795%2f1795725S.jpg&ratio=-1&pos=1&auto=True&quality=90"
[GORM] 2024/11/05 09:39:25 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[1.423ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "AVBASE" AND id = "lunatics:LULU-340" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:39:25 | 200 | 1.603835ms | 192.168.10.203 | GET "/v1/movies/AVBASE/lunatics:LULU-340?lazy=True"
[GORM] 2024/11/05 09:39:25 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[1.207ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "AVBASE" AND id = "lunatics:LULU-340" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:39:25 | 200 | 1.329092ms | 192.168.10.203 | GET "/v1/movies/AVBASE/lunatics:LULU-340?lazy=True"
[GORM] 2024/11/05 09:39:25 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[1.147ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "AVBASE" AND id = "lunatics:LULU-340" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:39:25 | 500 | 6.002362425s | 192.168.10.23 | GET "/v1/images/primary/JAV321/lulu00340?url=http%3a%2f%2fpics.dmm.co.jp%2fdigital%2fvideo%2flulu00340%2flulu00340ps.jpg&ratio=-1&pos=1&auto=True&quality=90"
[GIN] 2024/11/05 - 09:39:26 | 200 | 576.98982ms | 192.168.10.203 | GET "/v1/images/primary/AVBASE/lunatics:LULU-340?ratio=-1&pos=-1&auto=False&quality=90"
[GORM] 2024/11/05 09:39:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[1.246ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "AVBASE" AND id = "lunatics:LULU-340" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:39:26 | 200 | 308.639535ms | 192.168.10.203 | GET "/v1/images/thumb/AVBASE/lunatics:LULU-340?ratio=-1&pos=-1&auto=False&quality=90"
[GORM] 2024/11/05 09:39:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:202
[4.264ms] [rows:1] SELECT * FROM `movie_metadata` WHERE provider = "AVBASE" AND id = "lunatics:LULU-340" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
[GIN] 2024/11/05 - 09:39:27 | 200 | 385.891947ms | 192.168.10.203 | GET "/v1/images/backdrop/AVBASE/lunatics:LULU-340?ratio=-1&pos=-1&auto=False&quality=90"
```

**Comment by xjasonlyu** [comment]
试了一下，这个问题应该已经修复了。请确保插件和后端更新到最新版本，并重启。

**Comment by ohnggni** [comment]
It still doesn't work in Jellyfin 10.10.1 and latest plugin(2024.1031.200).

**Comment by xjasonlyu** [comment]
> It still doesn't work in Jellyfin 10.10.1 and latest plugin(2024.1031.200).

What's your error message and what is your backend server version? Could you provide more details, thanks.

**Comment by ohnggni** [comment]
> > It still doesn't work in Jellyfin 10.10.1 and latest plugin(2024.1031.200).
> 
> What's your error message and what is your backend server version? Could you provide more details, thanks.

This is a log in the jellyfin
`[23:07:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/@OffDn/AV by AI/SSNI-558/SSNI-558-U.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[23:07:00] [INF] [18] Jellyfin.Plugin.MetaTube.Providers.MovieProvider: Search for movie: SSNI-558
[23:07:03] [ERR] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Error in MetaTube
System.Net.Http.HttpRequestException: No route to host (192.168.1.173:8888)
 ---> System.Net.Sockets.SocketException (113): No route to host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MetaTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)`

There is NO log in the metatube. Not appeared anything.

**Comment by ohnggni** [comment]
> > It still doesn't work in Jellyfin 10.10.1 and latest plugin(2024.1031.200).
> 
> What's your error message and what is your backend server version? Could you provide more details, thanks.

Sorry. I overlooked that I recently have changed the ip address of the backend server.
Now the update works with Jellyfin 10.10.1 and the plugin. Thank you!!!!

**Comment by Yiomo** [comment]
> 试了一下，这个问题应该已经修复了。请确保插件和后端更新到最新版本，并重启。

解决了，plugins目录权限有问题导致插件没有正确更新到最新。
